from fastapi import FastAPI, Request, UploadFile, File, Form
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
import os
import json
import uuid

app = FastAPI(title="AI Workspace OS Core")

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_DIR = os.path.join(BASE_DIR, "static")

if os.path.exists(STATIC_DIR):
    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")

tasks_db = {}

AGENT_NETWORK = {
    "coordinator": {"name": "Coordinator Agent", "role": "Task Orchestration", "status": "Active"},
    "coder": {"name": "Coding Agent", "role": "Code & Logic Generation", "status": "Active (Qwen)"},
    "reviewer": {"name": "Reviewer Agent", "role": "Code Review & Safety", "status": "Ready"},
    "research": {"name": "Research Agent", "role": "Web Search & Synthesis", "status": "Standby"},
    "documenter": {"name": "Documenter Agent", "role": "Doc Formatting & Conversion", "status": "Ready"},
    "pc_control": {"name": "PC Control Agent", "role": "OS Automation (Level 2)", "status": "Ready"}
}

MEMORY_ENGINES = {
    "working": {"label": "Working Memory", "status": "Loaded", "capacity": "128k context"},
    "semantic": {"label": "Semantic Vector Store", "status": "Active (Qdrant/FAISS)", "vectors": 4200},
    "episodic": {"label": "Episodic Event Log", "status": "Recording", "events": 154},
    "device": {"label": "Device Registry", "status": "Windows Synced", "node": "Localhost"}
}

TOOL_REGISTRY = [
    {"id": "doc_converter", "name": "Document Converter", "status": "Enabled"},
    {"id": "collage_splitter", "name": "Collage Splitter", "status": "Enabled"},
    {"id": "image_editor", "name": "Image Editor", "status": "Enabled"},
    {"id": "logo_generator", "name": "Logo Generator", "status": "Enabled"}
]

SYSTEM_SETTINGS = {
    "ollama_host": "http://localhost:11434",
    "default_model": "qwen2.5:latest",
    "vector_store": "Qdrant / FAISS local",
    "event_bus_status": "Active",
    "log_level": "INFO"
}

@app.get("/api/health")
def health():
    return {"status": "ok", "ollama_bridge": SYSTEM_SETTINGS["ollama_host"]}

@app.get("/api/system/registry")
def get_registry():
    return {
        "agents": AGENT_NETWORK,
        "memory": MEMORY_ENGINES,
        "tools": TOOL_REGISTRY
    }

@app.get("/api/system/settings")
def get_settings():
    return SYSTEM_SETTINGS

@app.post("/api/system/settings")
async def update_settings(request: Request):
    data = await request.json()
    SYSTEM_SETTINGS.update(data)
    return JSONResponse({"status": "success", "settings": SYSTEM_SETTINGS})

@app.post("/api/terminal/execute")
async def execute_terminal(request: Request):
    data = await request.json()
    prompt = data.get("prompt", "")
    return JSONResponse({
        "status": "success",
        "log": f"[EXEC] Objective received: '{prompt}'\n[PLAN] Delegated to Coordinator -> Assigning sub-tasks...\n[COMPLETED] Pipeline run successful."
    })

@app.post("/api/tasks/create")
async def create_task(request: Request):
    data = await request.json()
    prompt = data.get("prompt", "")
    task_id = str(uuid.uuid4())[:8]
    
    execution_steps = [
        {"agent": "Coordinator", "log": f"Analyzing task: '{prompt}' and building execution tree..."},
        {"agent": "Coding Agent", "log": "Drafting code modules, scripts, and unit tests..."},
        {"agent": "Reviewer", "log": "Evaluating code quality, edge cases, and safety checks..."},
        {"agent": "Documenter", "log": "Generating Markdown README and final delivery package."}
    ]
    
    tasks_db[task_id] = {
        "id": task_id,
        "prompt": prompt,
        "status": "Completed",
        "pipeline": execution_steps,
        "output": f"### Task Execution Result\nCompleted processing for prompt: `{prompt}`.\n\n```python\n# Auto-generated by AI Agent Pipeline\ndef execute_task():\n    print('Task successfully executed across multi-agent workspace.')\n```"
    }
    return JSONResponse(tasks_db[task_id])

@app.get("/api/tasks")
def list_tasks():
    return list(tasks_db.values())

@app.post("/api/tools/convert-doc")
async def convert_document(
    source_format: str = Form(...),
    target_format: str = Form(...),
    file: UploadFile = File(None),
    raw_text: str = Form(None)
):
    content = ""
    if file:
        file_bytes = await file.read()
        content = file_bytes.decode("utf-8", errors="ignore")
    elif raw_text:
        content = raw_text
    else:
        return JSONResponse({"status": "error", "message": "No input file or text provided."}, status_code=400)

    converted_result = f"--- Converted from {source_format.upper()} to {target_format.upper()} ---\n\n"
    if target_format == "html":
        converted_result += f"<article>\n<h1>Converted Document</h1>\n<p>{content}</p>\n</article>"
    elif target_format == "json":
        converted_result += json.dumps({"status": "converted", "original_format": source_format, "content": content}, indent=2)
    elif target_format == "markdown":
        converted_result += f"# Document Output\n\n{content}"
    else:
        converted_result += content

    return JSONResponse({
        "status": "success",
        "source_format": source_format,
        "target_format": target_format,
        "result": converted_result
    })

@app.post("/api/tools/split-collage")
async def split_collage(file: UploadFile = File(...)):
    return JSONResponse({"status": "success", "message": f"Collage {file.filename} processed into 4 grid segments."})

@app.post("/api/tools/edit-image")
async def edit_image(file: UploadFile = File(...)):
    return JSONResponse({"status": "success", "message": f"Image enhancements applied to {file.filename}."})

@app.post("/api/tools/generate-logo")
async def generate_logo(request: Request):
    data = await request.json()
    logo_name = data.get("name", "Workspace Logo")
    return JSONResponse({"status": "success", "message": f"Generated high-res vector logo for: {logo_name}"})

@app.get("/", response_class=HTMLResponse)
def root():
    index_path = os.path.join(STATIC_DIR, "index.html")
    if os.path.exists(index_path):
        with open(index_path, "r", encoding="utf-8") as f:
            return f.read()
    return "<h1>Server running. Index file missing in static/</h1>"